server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: configClient
  cloud:
    config:
      name: dong
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config



