spring:
  datasource:
    druid:
      username: root
      password: password
      driver-class:
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      max-active: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/example/sam/*.xml
logging:
 # level:
 #  com.example.sam: debug
  config:  classpath:log/logback-spring.xml








