spring:
  datasource:
    druid:
      username: root
      password: password
      driver-class:
      url: jdbc:mysql://192.168.1.102:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      max-active: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 1
      break-after-acquire-failure: true
      connection-error-retry-attempts: 2
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  freemarker:
    suffix: .html
#  resources:
#    static-locations:  classpath:/login.html

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/example/sam/*.xml
logging:
 # level:
 #  com.example.sam: debug
  config:  classpath:log/logback-spring.xml


pagehelper:
  autoDialect: true
  closeConn: true
  offset-as-page-num : false




#
#shiro:
server:
  tomcat:
    max-connections: 1
#    threads:
#      max:
#  enabled: false
#shiro:
#  enabled:
#  loginUrl:
#dxs:
#  a: 6
jll: ${dxs.a:7}
