server:
  port: 8081

eureka:
  instance:
    hostname: configE
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kouwenjl/config.git
          username: dxsjl520@163.com
          password: dxs2019941314jll
#          search-paths: hh
#      name: dxs
#
#      label: master

